services:
  postgres-sorteador:
    image: postgres
    container_name: postgres-sorteador
    restart: always
    ports:
      - 3456:5432
    env_file:
      - back-end/.env
    volumes:
      - posgres-sorteador:/var/lib/posgresql/data

  node-sorteador:
    container_name: node-sorteador
    build: ./back-end
    ports:
      - 5000:5000
    depends_on:
      - postgres-sorteador
    env_file:
      - back-end/.env

  react-sorteador:
    container_name: react-sorteador
    build: ./front-end
    volumes:
      - build-react:/var/www/html

  nginx-sorteador:
    container_name: nginx-sorteador
    build: ./nginx
    ports:
      - 8080:80
    volumes:
      - build-react:/var/www/html
    depends_on:
      - postgres-sorteador
      - node-sorteador
      - react-sorteador

volumes:
  posgres-sorteador:
  build-react: