name: PullRequest
on: [pull_request]
jobs:
  PullRequest:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Make envfile
        uses: SpicyPizza/create-envfile@v1
        with:
          envkey_POSTGRES_USER: "postgres"
          envkey_POSTGRES_PASSWORD: "4815162342"
          envkey_POSTGRES_HOST: "postgres-sorteador"
          envkey_POSTGRES_PORT: "2345"
          envkey_POSTGRES_DATABASE: "students"
          envkey_DATABASE_URL: "postgresql://postgres:4815162342@postgres-sorteador:5432/students"
          directory: back-end/
          file_name: .env.test
          fail_on_empty: true

      - name: Run tests
        run: docker-compose -f docker-compose-test.yml run node-sorteador npm run test
      - name: Build
        run: npm i && npm run build